#I used the upper input with the adjective and animal to make them stand out. 
print()
print("Please enter the following: ")
print("To make the story funny try and use words that do not typically relate with one another.")
print()
adjective=input("adjective: ")
animal=input("animal: ")
verb1=input("verb #1: ")
exclamation=input("exclamation: ")
verb2=input("verb #2: ")
verb3=input("verb #3: ")
print()
print("Your story is: ")
print()
print(f"The other day, I was really in trouble. It all started when I saw a very {adjective.upper()} {animal.upper()} down the hallway. {exclamation.capitalize()}! \"I yelled.\" But all I could think to do was to {verb2} over and over. Miraculously, that caused it to stop, but not before it tried to {verb3} right in front of my family.")